INSERT INTO `Checklist` (`idChecklist`, `checkpointsNO`, `checkpointsEN`, `responsible`, `nationality`, `leader`) VALUES
  (NULL, 'Tilpasset liste og utpeking av roller.', 'Customized list and role distribution', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'SDI gir en konfirmasjon av at arbeidskontrakt har kommet tilbake.', 'SDI gives a confirmation that the contract of the new instated has been accepted', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Alt nødvendig lagt i personal mappen.', 'All necessary documents are delivered to his or her personnel file', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Registrering av ny bruker i BAS.', 'Registration of a new user in BAS (useradministrative system', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Orden på kontorplass og alt medfølgende.', 'Fix office space and everything that is accompanied by that.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Bestilling av IT-utsyr. Dette kan gjøres her: <a href="https://bestill.hioa.no/login.php">Bestilling</a>', 'Ordering of necessary IT equipment. Order it here: <a href="https://bestill.hioa.no/login.php">Order Here</a>', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Orientere til kollegaer.', 'Inform the colleagues.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Informasjon om oppmøte.', 'Information about attendance on the first day at the office.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Velkomsthilsen og sikkerhetsinformasjon.', 'Greetings and delivery of relevant classified information.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Velkomst med de nærmeste.', 'Greetings with your fellow co-workers.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Mailsystemet.', 'Introduction to the email system used at the work place.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Sjekk av IT-utstyr.Sjekk av IT-utstyr og test av IT kompetanse. Man kan teste de her: <a href="\&quot;https://tilsatt.hioa.no/ikt-nyansatte\&quot;">IT-Test</a>', Making sure that all IT equipment is working and in place. Make also sure that the new employee knows how to use it. Test: <a href="\&quot;https://tilsatt.hioa.no/en/it-newly-employed\&quot;">Test</a>', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Den generelle HMS opplæringen. Link til HMS sidene: <a href="https://tilsatt.hioa.no/a-a-hms">HMS</a>', 'Traning and introduction into the health and safety regulations at the faculty (HSE or HMS in Norwegian). The HSE pages can be found here: <a href="https://tilsatt.hioa.no/en/hse-a-z">HMS</a>', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Omvisning over hele arbeidsplassen.', 'A guided tour over the local office', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Et vennlig fjes hver dag.', 'Social contact from a familiar face.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Eget arbeidsforhold.', 'An orientation of your personal working space environment', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Den generelle HMS delen.', 'Training and introduction into the health and safety regulations at the faculty (HSE or HMS in Norwegian.', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Intranett introduksjon.', 'An introduction into the local intranet.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Opplæringsplan. Anbefalte kurs ligger her: <a href="https://tilsatt.hioa.no/oslomet-akademiet">Kurs</a>', 'Give the new co-worker information on recommended courses for the newly employee. Courses you can find here: <a href="\&quot;https://tilsatt.hioa.no/en/oslomet-academy\&quot;">Courses</a>', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Sosiale og kulturelle tilbud. Link her: <a href="\&quot;https://tilsatt.hioa.no/kultur-velferd\&quot;">Kulturllivet</a>', 'Share social and cultural events and offerings for the faculty. You can find them here: <a href="\&quot;https://tilsatt.hioa.no/en/culture-welfare\&quot;">Culture side of OsloMet</a>.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Arbeidsplassvurdering.', 'Ordering and reviewing of working space environment.', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Oppfølgings og informasjonssamtale.', 'A follow-up conversation about work situation and other necessary information.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Omvisning av alle studiestedene.', 'Guided tour of all the campuses.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Om nødvendig en ny oppfølgingsamtale.', 'If necessary at a later state another follow-up conversation.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Fadder gis samtidig som BAS registrering.', 'Mentor is given and informed to the new leader at the same time as the registration on BAS.', 'HR', 'Norsk', 'Ja'),
  (NULL, 'Lederen er med i planlegging av sin egen startperiode.', 'The newly recruited leader is included in planning of his own starting period.', 'HR', 'Norsk', 'Ja'),
  (NULL, 'Introduksjonsperm og tidligere innsikt i viktig informasjon.', 'Introductory folder and earlier access into vital information of the working space.', 'HR', 'Norsk', 'Ja'),
  (NULL, 'Dataprogram og riktige rettigheter.', 'Prepare the IT equipment with the necessary applications and access rights for the system in the faculty.', 'IKT', 'Norsk', 'Ja'),
  (NULL, 'Interessentanalyse.', 'Go through the stakeholder management for the university and the department and the schedules of meeting and events.', 'Leder', 'Norsk', 'Ja'),
  (NULL, 'Kompetanseutvikling/lederkurs.', 'Startup meeting with plan for development of skills by for example taking courses on leadership.', 'Leder', 'Norsk', 'Ja'),
  (NULL, 'Innføringsmoduler og rask kjennskap til sentrale prosesser.', 'Introduced to introductory modules in field of administrative work.', 'Leder', 'Norsk', 'Ja'),
  (NULL, 'Velkomstdokumenter og informasjon sendes på engelsk.', 'Welcome documents and information sent in English.', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Nasjonalitet skal registreres i registreringsskjema for rekruttering, på arbeidskontrakt og i SAP.', 'Nationality is included in the registration form for recruiting, workcontract and in SAP.', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Tilbud om assistanse for visum, ved behov, skal tilbys.', 'Offering to assist in a work-related visa.',
   'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Hjelp til bolig, norsk kurs og andre mottakstilbud. Linker:<a href="https://inn.chamber.no">Handelskammer</a> <a href="http://www.uio.no/english/for-employees/competence/overview-courses/languages/">N</a></td>', 'Assist in acquiring things in Norway. Useful links: <a href="\&quot;https://inn.chamber.no\&quot;">Commerce</a> <a href="\&quot;http://www.uio.no/english/for-employees/competence/overview-courses/languages/">Norwegian<!--</td--></a>', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Informasjon om BAS passord endringer. husk at man må ha registrert norsk mobilnummer <a href="https://www.hioa.no/minprofil">her</a> og trenger norsk D-eller fødselsnummer hvis ikke må BIT kontaktes.', 'Information of BAS password change. If the new recruited does not have a Norwegian cellphone and Norwegian D-number BIT must be contacted.', 'HR', 'Utenlandsk', 'Nei')

