INSERT INTO `checklist` (`idChecklist`, `checkpoints`, `responsible`, `language`, `leader`) VALUES
  (NULL, 'Tilpasset liste og utpeking av roller.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'SDI gir en konfirmasjon av at arbeidskontrakt har kommet tilbake.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Alt nødvendig lagt i personal mappen.', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Registrering av ny bruker i BAS.', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Orden på kontorplass og alt medfølgende.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Bestilling av IT-utstyr.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Orientere til kollegaer.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Informasjon om oppmøte.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Velkomsthilsen og sikkerhetsinformasjon.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Velkomst med de nærmeste.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Mailsystemet.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Sjekk av IT-utstyr.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'HMS-opplæring grunnleggende.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Omvisning over hele arbeidsplassen.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Et vennlig fjes hver dag.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Eget arbeidsforhold.', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Den generelle HMS delen.', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Intranett introduksjon.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Opplæringsplan.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Sosiale og kulturelle tilbud.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Arbeidsplassvurdering.', 'HR', 'Norsk', 'Nei'),
  (NULL, 'Oppfølgings og informasjonssamtale.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Omvisning av alle studiestedene.', 'Fadder', 'Norsk', 'Nei'),
  (NULL, 'Om nødvendig en ny oppfølgingsamtale.', 'Leder', 'Norsk', 'Nei'),
  (NULL, 'Fadder gis samtidig som BAS registrering.', 'HR', 'Norsk', 'Ja'),
  (NULL, 'Lederen er med i planlegging av sin egen startperiode.', 'HR', 'Norsk', 'Ja'),
  (NULL, 'Introduksjonsperm og tidligere innsikt i viktig informasjon.', 'HR', 'Norsk', 'Ja'),
  (NULL, 'Dataprogram og riktige rettigheter.', 'IKT', 'Norsk', 'Ja'),
  (NULL, 'Interessentanalyse.', 'Leder', 'Norsk', 'Ja'),
  (NULL, 'Kompetanseutvikling/lederkurs.', 'Leder', 'Norsk', 'Ja'),
  (NULL, 'Innføringsmoduler og rask kjennskap til sentrale prosesser.', 'Leder', 'Norsk', 'Ja'),
  (NULL, 'Velkomstdokumenter og informasjon sendes på engelsk.', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Nasjonalitet skal registreres i registreringsskjema for rekruttering, på arbeidskontrakt og i SAP.', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Tilbud om assistanse for visum, ved behov, skal tilbys.', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Tilbud om hjelp til bolig, norsk kurs og andre mottakstilbud skal vurderes ref. HiOA’s rammeavtale med Oslo Handelskammer for intl. mottak og UiO’s «Norwegian for Academics».', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'BAS passord - hvis den tilsatte har glemt passordet husk at man må ha registrert norsk mobilnummer i https://www.hioa.no/minprofil og trenger norsk D-eller fødselsnummer for å kunne bruke løsningen. Mangler det må BIT kontaktes for å få nytt passord.', 'HR', 'Utenlandsk', 'Nei'),
  (NULL, 'Customized list and role distribution.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'SDI gives a confirmation that the contract of the new instated has been accepted.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'All necessary documents are delivered to his or her personnel file.', 'HR', 'Engelsk', 'Nei'),
  (NULL, 'Registration of a new user in BAS (useradministrative system).', 'HR', 'Engelsk', 'Nei'),
  (NULL, 'Fix office space and everything that is accompanied by that.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Ordering of necessary IT equipment.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Inform the colleagues.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Information about attendance on the first day at the office.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'Greetings and delivery of relevant classified information.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Greetings with your fellow co-workers.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'Introduction to the email system used at the work place.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Making sure that all IT equipment is working and in place.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'A basic introduction to fire emergencies protocols.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'A guided tour over the local office.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'Social contact from a familiar face.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'An orientation of your personal working space environment.', 'HR', 'Engelsk', 'Nei'),
  (NULL, 'Training and introduction into the health and safety regulations at the faculty (HSE or HMS in Norwegian).', 'HR', 'Engelsk', 'Nei'),
  (NULL, 'An introduction into the local intranet.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'Give the new co-worker information on recommended courses for the newly employee and sign up to an introductory day for the newly employed.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Share social and cultural events and offerings for the faculty.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'Ordering and reviewing of working space environment.', 'HR', 'Engelsk', 'Nei'),
  (NULL, 'A follow-up conversation about work situation and other necessary information.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Guided tour of all the campuses.', 'Mentor', 'Engelsk', 'Nei'),
  (NULL, 'If necessary at a later state another follow-up conversation.', 'Leader', 'Engelsk', 'Nei'),
  (NULL, 'Mentor is given and informed to the new leader at the same time as the registration on BAS', 'HR', 'Engelsk', 'Ja'),
  (NULL, 'The newly recruited leader is included in planning of his own starting period.', 'HR', 'Engelsk', 'Ja'),
  (NULL, 'Introductory folder and earlier access into vital information of the working space.', 'HR', 'Engelsk', 'Ja'),
  (NULL, 'Prepare the IT equipment with the necessary applications and access rights for the system in the faculty.', 'Leader', 'Engelsk', 'Ja'),
  (NULL, 'Go through the stakeholder management for the university and the department and the schedules of meeting and events.', 'Leader', 'Engelsk', 'Ja'),
  (NULL, 'Startup meeting with plan for development of skills by for example taking courses on leadership.', 'Leader', 'Engelsk', 'Ja'),
  (NULL, 'Introduced to introductory modules in field of administrative work.', 'Leader', 'Engelsk', 'Ja'),
  (NULL, 'Welcome documents and information sent in English.', 'HR', 'Foreign', 'Nei'),
  (NULL, 'Nationality is included in the registration form for recruiting, workcontract and in SAP.', 'HR', 'Foreign', 'Nei'),
  (NULL, 'Offering to assist in a work-related visa.', 'HR', 'Foreign', 'Nei'),
  (NULL, 'Offering to assist in acquiring an apartment. HR department will use their treaty with Oslo chamber of commerce as a building block.', 'HR', 'Foreign', 'Nei'),
  (NULL, 'Information of BAS password change. If the new recruited does not have a Norwegian cellphone and Norwegian D-number BIT must be contacted.', 'Leader', 'Foreign', 'Nei')