INSERT INTO `checklist` (`idChecklist`, `checkpointsNO`, `checkpointsEN`, `responsible`, `language`, `leader`) VALUES 
(NULL, 'Tilpasset liste og utpeking av roller.', 'Customized list and role distribution', 'Leder', 'Norsk', 'Nei'), 
(NULL, 'SDI gir en konfirmasjon av at arbeidskontrakt har kommet tilbake.', 'SDI gives a confirmation that the contract of the new instated has been accepted', 'Leder', 'Norsk', 'Nei'), 
(NULL, 'Alt nødvendig lagt i personal mappen.', 'All necessary documents are delivered to his or her personnel file', 'HR', 'Norsk', 'Nei'), 
(NULL, 'Registrering av ny bruker i BAS.', 'Registration of a new user in BAS (useradministrative system', 'HR', 'Norsk', 'Nei'),  
(NULL, 'Orden på kontorplass og alt medfølgende.', 'Fix office space and everything that is accompanied by that.', 'Leder', 'Norsk', 'Nei'), 
(NULL, 'Bestilling av IT-utstyr.', 'Ordering of necessary IT equipment.', 'Leder', 'Norsk', 'Nei'), 
(NULL, 'Orientere til kollegaer.', 'Inform the colleagues.', 'Leder', 'Norsk', 'Nei'), 
(NULL, 'Informasjon om oppmøte.', 'Information about attendance on the first day at the office.', 'Fadder', 'Norsk', 'Nei'), 
(NULL, 'Velkomsthilsen og sikkerhetsinformasjon.', 'Greetings and delivery of relevant classified information.', 'Leder', 'Norsk', 'Nei'), 
(NULL, 'Velkomst med de nærmeste.', 'Greetings with your fellow co-workers.', 'Fadder', 'Norsk', 'Nei'),
(NULL, 'Mailsystemet.', 'Introduction to the email system used at the work place.', 'Leder', 'Norsk', 'Nei'),
(NULL, 'Sjekk av IT-utstyr.', 'Making sure that all IT equipment is working and in place.', 'Fadder', 'Norsk', 'Nei'),
(NULL, 'HMS-opplæring grunnleggende.', 'A basic introduction to fire emergencies protocols.', 'Leder', 'Norsk', 'Nei'),
(NULL, 'Omvisning over hele arbeidsplassen.', 'A guided tour over the local office', 'Fadder', 'Norsk', 'Nei'),
(NULL, 'Et vennlig fjes hver dag.', 'Social contact from a familiar face.', 'Fadder', 'Norsk', 'Nei'),
(NULL, 'Eget arbeidsforhold.', 'An orientation of your personal working space environment', 'HR', 'Norsk', 'Nei'),
(NULL, 'Den generelle HMS delen.', 'Training and introduction into the health and safety regulations at the faculty (HSE or HMS in Norwegian.', 'HR', 'Norsk', 'Nei'),
(NULL, 'Intranett introduksjon.', 'An introduction into the local intranet.', 'Fadder', 'Norsk', 'Nei'),
(NULL, 'Opplæringsplan.', 'Give the new co-worker information on recommended courses for the newly employee and sign up to an introductory day for the newly employed.', 'Leder', 'Norsk', 'Nei'),
(NULL, 'Sosiale og kulturelle tilbud.', 'Share social and cultural events and offerings for the faculty.', 'Fadder', 'Norsk', 'Nei'),
(NULL, 'Arbeidsplassvurdering.', 'Ordering and reviewing of working space environment.', 'HR', 'Norsk', 'Nei'),
(NULL, 'Oppfølgings og informasjonssamtale.', 'A follow-up conversation about work situation and other necessary information.', 'Leder', 'Norsk', 'Nei'),
(NULL, 'Omvisning av alle studiestedene.', 'Guided tour of all the campuses.', 'Fadder', 'Norsk', 'Nei'),
(NULL, 'Om nødvendig en ny oppfølgingsamtale.', 'If necessary at a later state another follow-up conversation.', 'Leder', 'Norsk', 'Nei'),
(NULL, 'Fadder gis samtidig som BAS registrering.', 'Mentor is given and informed to the new leader at the same time as the registration on BAS.', 'HR', 'Norsk', 'Ja'),
(NULL, 'Lederen er med i planlegging av sin egen startperiode.', 'The newly recruited leader is included in planning of his own starting period.', 'HR', 'Norsk', 'Ja'),
(NULL, 'Introduksjonsperm og tidligere innsikt i viktig informasjon.', 'Introductory folder and earlier access into vital information of the working space.', 'HR', 'Norsk', 'Ja'),
(NULL, 'Dataprogram og riktige rettigheter.', 'Prepare the IT equipment with the necessary applications and access rights for the system in the faculty.', 'IKT', 'Norsk', 'Ja'),
(NULL, 'Interessentanalyse.', 'Go through the stakeholder management for the university and the department and the schedules of meeting and events.', 'Leder', 'Norsk', 'Ja'),
(NULL, 'Kompetanseutvikling/lederkurs.', 'Startup meeting with plan for development of skills by for example taking courses on leadership.', 'Leder', 'Norsk', 'Ja'),
(NULL, 'Innføringsmoduler og rask kjennskap til sentrale prosesser.', 'Introduced to introductory modules in field of administrative work.', 'Leder', 'Norsk', 'Ja'),
(NULL, 'Velkomstdokumenter og informasjon sendes på engelsk.', 'Welcome documents and information sent in English.', 'HR', 'Utenlandsk', 'Nei'),
(NULL, 'Nasjonalitet skal registreres i registreringsskjema for rekruttering, på arbeidskontrakt og i SAP.', 'Nationality is included in the registration form for recruiting, workcontract and in SAP.', 'HR', 'Utenlandsk', 'Nei'),
(NULL, 'Tilbud om assistanse for visum, ved behov, skal tilbys.', 'Offering to assist in a work-related visa.',
'HR', 'Utenlandsk', 'Nei'),
(NULL, 'Tilbud om hjelp til bolig, norsk kurs og andre mottakstilbud skal vurderes ref. HiOA’s rammeavtale med Oslo Handelskammer for intl. mottak og UiO’s «Norwegian for Academics».', 'Offering to assist in acquiring an apartment. HR department will use their treaty with Oslo chamber of commerce as a building block.', 'HR', 'Utenlandsk', 'Nei'),
(NULL, 'BAS passord - hvis den tilsatte har glemt passordet husk at man må ha registrert norsk mobilnummer i https://www.hioa.no/minprofil og trenger norsk D-eller fødselsnummer for å kunne bruke løsningen. Mangler det må BIT kontaktes for å få nytt passord.', 'Information of BAS password change. If the new recruited does not have a Norwegian cellphone and Norwegian D-number BIT must be contacted.', 'HR', 'Utenlandsk', 'Nei')
